title: AIs Through the Looking Glass
description: Artificial intelligence in more ways than one
permalink: /posts/:title/
future: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  skin: auto
  show_excerpts: true
  nav_pages:
    - about.md
  social_links:
    github: pro-cert-notes
    rss: true
    
feed:
  excerpt_only: true
