title: AIs Through the Looking Glass
description: Artificial intelligence in more ways than one

plugins:
  - jekyll-remote-theme

markdown: GFM

remote_theme: jekyll/minima

minima:
  skin: auto
  show_excerpts: true
  nav_pages:
    - about.md
