title: AIs Through the Looking Glass
description: Artificial intelligence in more ways than one

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  show_excerpts: true
  nav_pages:
    - about.md
