title: AIs Through the Looking Glass
description: Artificial intelligence in more ways than one

plugins:
  - jekyll-remote-theme
  - jekyll-feed

excerpt_only: true

remote_theme: jekyll/minima
minima:
  skin: auto
  show_excerpts: true
  nav_pages:
    - about.md
