title: AIs Through the Looking Glass
description: Artifical intelligence in more ways than one

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  hide_site_feed_link: true
  show_excerpts: true
  nav_pages:
    - about.md
