title: AIs Through the Looking Glass
description: Artificial intelligence in more ways than one

plugins:
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: jekyll/minima
minima:
  skin: auto
  show_excerpts: true
  nav_pages:
    - about.md

social_links:
    - title: GitHub Repos
      icon: github
      url: "https://github.com/pro-cert-notes/"
